shared:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>

development:

test:

production:
  telegram:
    bot:
      token: <%= ENV.fetch("TELEGRAM_BOT_TOKEN") %>
